--- #YAML:1.0
name:               B-RecDeparse
version:            0.04
abstract:           Deparse recursively into subroutines.
author:
    - Vincent Pit <perl@profvince.com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    B::Deparse:  0
    Carp:        0
    Config:      0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
build_requires:
    ExtUtils::MakeMaker:           0
    Test::More:                    0
