--- #YAML:1.0
name:               B-RecDeparse
version:            0.05
abstract:           Deparse recursively into subroutines.
author:
    - Vincent Pit <perl@profvince.com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    B::Deparse:           0
    base:                 0
    Carp:                 0
    Config:               0
    ExtUtils::MakeMaker:  0
    Test::More:           0
requires:
    B::Deparse:  0
    base:        0
    Carp:        0
    Config:      0
    perl:        5.008001
resources:
    bugtracker:  http://rt.cpan.org/NoAuth/ReportBug.html?Queue=B-RecDeparse
    homepage:    http://search.cpan.org/dist/B-RecDeparse/
    license:     http://dev.perl.org/licenses/
    repository:  http://git.profvince.com/?p=perl%2Fmodules%2FB-RecDeparse.git
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
dynamic_config:     0
